site_name: "USTC OS Docs"
site_description: "中国科学技术大学操作系统课程实验文档"
site_author: "USTC OS Team"

use_directory_urls: false

theme:
  name: 'material'
  language: 'zh'

markdown_extensions:
  - admonition
  - markdown_gfm_admonition
  - pymdownx.details
  - pymdownx.superfences
