site_name: "USTC OS Docs"
site_description: "中国科学技术大学操作系统课程实验文档"
site_author: "USTC OS Team"

use_directory_urls: false

theme:
  name: 'material'
  language: 'zh'

markdown_extensions:
  - admonition
  - markdown_gfm_admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 简介: index.md
  - 实验一:
    - "Part1 环境准备": vmlab/vmlab.md
    - "Part2 实现Shell": shelllab/shellab.md
    - "Part3 实现系统调用": syscalllab/syscalllab.md
  - 实验二: malloclab/malloclab.md
  - 实验三:
    - "Part1 开源鸿蒙初探": ohlab/ohlab-part1.md
    - "Part2 端侧推理应用实现": ohlab/ohlab-part2.md
    - "附录": ohlab/appendix.md

dev_addr: 127.0.0.1:9999
